DROP TABLE ATABLE ;

CREATE TABLE ATABLE 
(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
, INS_DATE DATE NOT NULL 
, INFO_CI VARCHAR2(100)
, CONSTRAINT ATABLE_PK PRIMARY KEY (ID) ENABLE 
);

select id, info_ci, TO_CHAR(ins_date, 'DD/MM/YYYY HH24:MI:SS') ins_date from ATABLE order by id desc;
